package spl.semantic;

import java.util.Objects;
import spl.tree.TreeNode;

public final class Symbol {
    private final String originalName; //lexeme
    private final String generatedName; //ID generated by our program
    private final SymbolKind kind; // var/func etc
    private final Scope declaringScope; //where was I declared
    private final TreeNode declarationNode; // point to the syntax-tree node that created it
    private SemanticType type; //start with unkown and then later updated in phase 2b

    public Symbol(String originalName, String generatedName, SymbolKind kind, Scope declaringScope, TreeNode declarationNode) {
        this.originalName = requireName(originalName, "originalName");
        this.generatedName = requireName(generatedName, "generatedName");
        this.kind = Objects.requireNonNull(kind, "kind");
        this.declaringScope = Objects.requireNonNull(declaringScope, "declaringScope");
        this.declarationNode = declarationNode;
        this.type = SemanticType.UNKNOWN;
    }

    public String getOriginalName() {
        return originalName;
    }

    public String getGeneratedName() {
        return generatedName;
    }

    public SymbolKind getKind() {
        return kind;
    }

    public Scope getDeclaringScope() {
        return declaringScope;
    }

    public TreeNode getDeclarationNode() {
        return declarationNode;
    }

    public SemanticType getType() {
        return type;
    }

    /** Updates the type inferred by a later semantic-analysis phase. */
    public void setType(SemanticType type) {
        this.type = Objects.requireNonNull(type, "type");
    }

    @Override
    public String toString() {
        return kind + " " + originalName + " -> " + generatedName + " (" + type + ")";
    }

    private static String requireName(String name, String field) {
        Objects.requireNonNull(name, field);
        if (name.isBlank()) {
            throw new IllegalArgumentException(field + " must not be blank");
        }
        return name;
    }
}
